Changed a few commands
DaRealTurtyWurty/SuperTurtyBot pull request #262
Opened 2024-10-18 07:05 UTC by O7410

look at the commit names

2024-10-19 21:17 UTC, DaRealTurtyWurty requested changes

2024-10-19 21:17 UTC, DaRealTurtyWurty commented on src/main/java/dev/darealturtywurty/superturtybot/commands/economy/CrimeCommand.java
> +                    (jobLevel != newJobLevel ? "\n\n❌ You have been demoted to level %d (%d levels) from your job!".formatted(newJobLevel, newJobLevel - jobLevel) : ""));
```suggestion
                    (jobLevel != newJobLevel ? "\n\n❌ You have been demoted by %d levels to level %d in your current job.".formatted(newJobLevel - jobLevel, newJobLevel) : ""));
```

2024-10-20 09:13 UTC, O7410 commented on src/main/java/dev/darealturtywurty/superturtybot/commands/economy/CrimeCommand.java
> +                    (jobLevel != newJobLevel ? "\n\n❌ You have been demoted to level %d (%d levels) from your job!".formatted(newJobLevel, newJobLevel - jobLevel) : ""));
currently this will say:
❌ You have been demoted by -2 levels to level 3 in your current job.
(for example)
maybe it should be `jobLevel - newJobLevel` to show the demoted levels amount as a positive number

2024-10-20 12:51 UTC, DaRealTurtyWurty commented on src/main/java/dev/darealturtywurty/superturtybot/commands/economy/CrimeCommand.java
> +                    (jobLevel != newJobLevel ? "\n\n❌ You have been demoted to level %d (%d levels) from your job!".formatted(newJobLevel, newJobLevel - jobLevel) : ""));
Yeah I suppose that might be better

2024-10-20 13:17 UTC, O7410 commented
I committed it

2024-10-20 13:21 UTC, merged